Repository AthennaIO/Cli, pull requests merged in 2023-01, with the labels that each got.

#40 fix(resources): adjust component templates
  app/Console/Commands/Install/DatabaseCommand.js
  app/Console/Commands/Install/MailCommand.js
  package-lock.json
  package.json
  resources/scaffolds/databaseComponent/mongo/config/database.js
  resources/scaffolds/databaseComponent/mongo/docker-compose.yml
  resources/scaffolds/mailComponent/config/mail.js
Labels: fix

#44 Update dependencies and change clone URL
  app/Console/Commands/Install/DatabaseCommand.js
  app/Console/Commands/Install/MailCommand.js
  app/Console/Commands/NewCommand.js
  app/Console/Kernel.js
  package-lock.json
  package.json
  tests/main.js
Labels: feature, refactor

#45 chore(npm): update dependencies
  app/Console/Commands/Install/DatabaseCommand.js
  app/Console/Commands/Install/MailCommand.js
  app/Console/Commands/NewCommand.js
  app/Console/Exceptions/Handler.js
  app/Console/Kernel.js
  app/Exceptions/NotEmptyFolderException.js
  app/Exceptions/NotFoundDatabaseException.js
  app/Exceptions/NotFoundProjectTypeException.js
  artisan.js
  bootstrap/main.js
  config/app.js
  config/logging.js
  package-lock.json
  package.json
  providers/AppServiceProvider.js
  routes/console.js
  tests/E2E/Install/InstallDatabaseCommandTest.js
  tests/E2E/Install/InstallMailCommandTest.js
  tests/E2E/NewCommandTest.js
  tests/Stubs/.gitkeep
  tests/main.js
Labels: chore

#46 chore(npm): update dependencies
  app/Console/Kernel.js
  package-lock.json
  package.json
Labels: chore

#48 chore(npm): update dependencies
  app/Console/Commands/Install/DatabaseCommand.js
  app/Console/Kernel.js
  package-lock.json
  package.json
Labels: chore

#52 Feat/vic version validator
  app/Helpers/VersionUpdateHelper.js
  bootstrap/main.js
Labels: feature

#53 Feat/vic create update command
  app/Console/Commands/UpdateCommand.js
Labels: feature

#54 feat: standardize dependencies versions control
  package.json
Labels: feature
